server:
  servlet:
    context-path: /dev

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/shortenerdb
    username: ${DB_USER:shorteneruser}
    password: ${DB_PASSWORD:shortenerpassword}
    driver-class-name: org.postgresql.Driver
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true