spring:
  # Database H2 configuration in-memory
  datasource:
    url: jdbc:h2:mem:urlshortenerdb # Database H2 in-memory
    driverClassName: org.h2.Driver
    username: sa
    password: password
    platform: h2

  # JPA Configuration for H2
  jpa:
    # CRUCIAL: Tells Spring where to find entities
    packages-to-scan: org.dkb

    hibernate:
      # create-drop -> necessary to re-create table at each restart
      ddl-auto: create-drop
      database-platform: org.hibernate.dialect.H2Dialect

    # Hibernate additional properties
    properties:
      hibernate.dialect.storage_engine: innodb

  # Redis local configuration
  data:
    redis:
      host: localhost
      port: 6379

logging:
  level:
    # Log level for package
    org.dkb: DEBUG
    org.springframework.web: INFO
    org.hibernate: INFO