server:
  port: 8080
  error:
    include-message: always

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /shortify/api-docs
  info:
    title: Shortify API
    version: v1.0.0
    description: API to shorten URL.

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  # TODO: comment the lines below to enable redis
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration
